-- ============================================================================
-- MIGRATION VERIFIER — Planners Dashboard
-- Generated 2026-08-27 from every migrations/2026-07-*.sql and 2026-08-*.sql file.
--
-- Paste the whole file into the Supabase SQL editor and run it. IT WRITES NOTHING.
-- It returns one row per migration whose declared tables / columns / functions are
-- not all present, naming exactly which objects are missing.
--
-- NO ROWS RETURNED = every migration in the repo is applied. Any row listed is a
-- migration that has not been fully applied: run that file, then re-run this.
--
-- ⚠️ IT CHECKS OBJECT EXISTENCE ONLY — not RLS policies, grants, index definitions,
--    trigger bodies or back-fills. A file can look complete here and still have had
--    its policy block skipped, so read a clean result as "the schema is there", not
--    as "every migration ran end to end".
-- ⚠️ A column is only checked when its TABLE exists. A missing table is reported once
--    as a missing table rather than dragging every one of its columns in behind it.
-- ============================================================================
with expected(migration, kind, obj, col) as (values
    ('2026-07-01-resource-role-master.sql','table','resource_roles',''),
    ('2026-07-01-resource-role-master.sql','table','resources',''),
    ('2026-07-02-baseline-cost-column.sql','column','project_schedule','bl_cost'),
    ('2026-07-03-resource-assignments.sql','table','resource_assignments',''),
    ('2026-07-06-working-calendars.sql','table','calendars',''),
    ('2026-07-06-working-calendars.sql','column','resources','calendar_id'),
    ('2026-07-06-working-calendars.sql','column','project_schedule','calendar_id'),
    ('2026-07-07-activity-codes.sql','table','activity_code_types',''),
    ('2026-07-07-activity-codes.sql','table','activity_code_values',''),
    ('2026-07-07-activity-codes.sql','column','project_schedule','activity_codes'),
    ('2026-07-07-activity-steps.sql','table','activity_steps',''),
    ('2026-07-07-assignment-curve.sql','column','resource_assignments','curve'),
    ('2026-07-07-risk-3point-duration.sql','column','project_schedule','risk_optimistic_pct'),
    ('2026-07-07-risk-3point-duration.sql','column','project_schedule','risk_pessimistic_pct'),
    ('2026-07-07-schedule-audit.sql','table','schedule_audit',''),
    ('2026-07-07-schedule-baselines.sql','table','schedule_baselines',''),
    ('2026-07-07-schedule-contract-date.sql','column','project_schedule','contract_date'),
    ('2026-07-07-schedule-scenarios.sql','table','schedule_scenarios',''),
    ('2026-07-07-schedule-snapshots.sql','table','schedule_snapshots',''),
    ('2026-07-07-schedule-thresholds.sql','table','schedule_thresholds',''),
    ('2026-07-07-user-defined-fields.sql','table','activity_udf_defs',''),
    ('2026-07-07-user-defined-fields.sql','column','project_schedule','udf'),
    ('2026-07-07-wbs-nodes.sql','table','wbs_nodes',''),
    ('2026-07-07-wbs-nodes.sql','column','project_schedule','wbs_node_id'),
    ('2026-07-07-weekly-commitments.sql','table','weekly_commitments',''),
    ('2026-07-11-activity-seq-order.sql','column','project_schedule','seq_order'),
    ('2026-07-11-portfolio-resource-rpc.sql','function','portfolio_resource_summary',''),
    ('2026-07-11-resource-cost-parity.sql','table','cost_accounts',''),
    ('2026-07-11-resource-cost-parity.sql','table','activity_expenses',''),
    ('2026-07-11-resource-cost-parity.sql','column','resources','price_per_unit'),
    ('2026-07-11-resource-cost-parity.sql','column','resource_roles','price_per_unit'),
    ('2026-07-11-resource-cost-parity.sql','column','resource_assignments','budgeted_cost'),
    ('2026-07-11-resource-cost-parity.sql','column','resource_assignments','actual_cost'),
    ('2026-07-11-resource-cost-parity.sql','column','resource_assignments','remaining_cost'),
    ('2026-07-11-resource-cost-parity.sql','column','resource_assignments','cost_account_id'),
    ('2026-07-11-resource-cost-parity.sql','column','resource_assignments','rate_source'),
    ('2026-07-11-resource-cost-parity.sql','column','project_schedule','cost_rollup'),
    ('2026-07-14-billing-milestones.sql','table','cash_flow_billing_milestones',''),
    ('2026-07-14-billing-milestones.sql','column','cash_flow_settings','billing_basis'),
    ('2026-07-14-cash-flow-dp-tranches.sql','table','cash_flow_dp_tranches',''),
    ('2026-07-14-cash-flow-settings.sql','table','cash_flow_settings',''),
    ('2026-07-14-cash-flow-v2.sql','table','cash_flow_actuals',''),
    ('2026-07-14-cash-flow-v2.sql','table','cash_flow_rollup',''),
    ('2026-07-14-cash-flow-v2.sql','column','cash_flow_settings','ewt_percent'),
    ('2026-07-14-cash-flow-v2.sql','column','cash_flow_settings','vat_percent'),
    ('2026-07-14-cash-flow-v2.sql','column','cash_flow_settings','ret_rel1_pct'),
    ('2026-07-14-cash-flow-v2.sql','column','cash_flow_settings','ret_rel2_months'),
    ('2026-07-14-cash-flow-v3.sql','table','cash_flow_trade_packages',''),
    ('2026-07-14-cash-flow-v3.sql','table','cash_flow_scenarios',''),
    ('2026-07-14-cash-flow-v3.sql','column','cash_flow_settings','finance_rate'),
    ('2026-07-14-cash-flow-v3.sql','column','cash_flow_settings','funding_limit'),
    ('2026-07-14-cash-flow-v3.sql','column','cash_flow_settings','scurve_basis'),
    ('2026-07-14-cashflow-schedule-agg-rpc.sql','function','cashflow_schedule_agg',''),
    ('2026-07-14-cashout-retention-stages.sql','column','cash_flow_settings','co_ret_rel1_pct'),
    ('2026-07-14-cashout-retention-stages.sql','column','cash_flow_settings','co_ret_rel1_months'),
    ('2026-07-14-cashout-retention-stages.sql','column','cash_flow_settings','co_ret_rel2_months'),
    ('2026-07-14-ev-poc.sql','column','project_schedule','ev_poc'),
    ('2026-07-14-trade-dp-tranches.sql','column','cash_flow_trade_packages','dp_tranches'),
    ('2026-07-14-wpm-mirror-award-status.sql','column','wpm_work_packages','award_status'),
    ('2026-07-14-wpm-mirror-award-status.sql','column','wpm_work_packages','procurement_status'),
    ('2026-07-14-wpm-mirror-award-status.sql','column','wpm_work_packages','delivery_status'),
    ('2026-07-14-wpm-mirror-trade.sql','column','wpm_work_packages','trade'),
    ('2026-07-14-wpm-work-packages-mirror.sql','table','wpm_work_packages',''),
    ('2026-07-16-consolidated.sql','table','wbs_nodes',''),
    ('2026-07-16-consolidated.sql','column','project_schedule','wbs_node_id'),
    ('2026-07-16-consolidated.sql','function','admin_archive_project',''),
    ('2026-07-16-consolidated.sql','function','admin_delete_project',''),
    ('2026-07-16-consolidated.sql','function','admin_delete_workspace',''),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','proj_code'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','building_ref'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','company'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','drawing_type'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','floor_level'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','dwg_number'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','drawing_code'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','phase'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','category'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','description'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','responsible'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','no_of_sheets'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','approved_sheets'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','approved_pct'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','submissions'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','planned_approval'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','actual_approval'),
    ('2026-07-16-drawing-register-full.sql','column','drawing_register','sort_order'),
    ('2026-07-16-drawing-register-nodes.sql','column','drawing_register','node_kind'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','department'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','champion'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','caused_by'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','corrective_action'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','date_presented'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','date_resolved'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','lesson_learned'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','lesson_category'),
    ('2026-07-17-issues-lessons.sql','column','issues_lessons','recommendation'),
    ('2026-07-17-ppr-presentations.sql','table','ppr_presentations',''),
    ('2026-07-17-ppr-presentations.sql','table','ppr_slides',''),
    ('2026-07-17-progress-photos.sql','column','progress_photos','trade'),
    ('2026-07-17-progress-photos.sql','column','progress_photos','works'),
    ('2026-07-17-progress-photos.sql','column','progress_photos','sort_order'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','est_amount'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','sub_amount'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','eval_amount'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','approved_amount'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','est_days'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','sub_days'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','eval_days'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','approved_days'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','date_submitted'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','date_evaluated'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','date_approved'),
    ('2026-07-20-contracts-claims-full.sql','column','contracts_claims','sort_order'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_project'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_building'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_company'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_doctype'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_discipline'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_floor'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','code_number'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','trade_section'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','discipline'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','trade_code'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','floor_levels'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','location'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','reference_document'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','brand'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','type_presentation'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','plan_submission_date'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','plan_approval_date'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','approver_consultant'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','approver_client'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','revision_no'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','mas_id'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','seq_no'),
    ('2026-07-20-material-submittal-full.sql','column','material_submittal','sort_order'),
    ('2026-07-20-productivity-rates-full.sql','table','productivity_activities',''),
    ('2026-07-20-productivity-rates-full.sql','table','productivity_entries',''),
    ('2026-07-20-schedule-scurve-agg.sql','function','schedule_scurve_agg_multi',''),
    ('2026-07-20-schedule-scurve-agg.sql','function','schedule_scurve_agg',''),
    ('2026-07-20-schedule-scurve-agg.sql','function','cashflow_schedule_agg',''),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','stakeholder_group'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','title'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','nickname'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','birthday'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','email'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','current_rel'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','target_rel'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','primary_responsible'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','alternate'),
    ('2026-07-20-stakeholder-map-full.sql','column','stakeholder_map','gift_tier'),
    ('2026-07-21-viewer-readonly.sql','function','is_writer',''),
    ('2026-07-22-schedule-rows-rpc.sql','function','schedule_rows',''),
    ('2026-07-23-schedule-builder.sql','table','schedule_builder',''),
    ('2026-07-25-schedule-document-links.sql','column','drawing_register','schedule_activity_id'),
    ('2026-07-25-schedule-document-links.sql','column','drawing_register','schedule_wbs'),
    ('2026-07-25-schedule-document-links.sql','column','drawing_register','lead_days'),
    ('2026-07-25-schedule-document-links.sql','column','material_submittal','schedule_activity_id'),
    ('2026-07-25-schedule-document-links.sql','column','material_submittal','schedule_wbs'),
    ('2026-07-25-schedule-document-links.sql','column','material_submittal','lead_days'),
    ('2026-08-03-wbs-skeleton.sql','column','wbs_nodes','is_locked'),
    ('2026-08-03-wbs-skeleton.sql','column','wbs_nodes','source_kind'),
    ('2026-08-04-activity-location-work-type.sql','table','location_levels',''),
    ('2026-08-04-activity-location-work-type.sql','column','project_schedule','location'),
    ('2026-08-04-activity-location-work-type.sql','column','project_schedule','work_type'),
    ('2026-08-05-drawing-register-sheets.sql','column','drawing_register','parent_id'),
    ('2026-08-05-location-level-match.sql','column','location_levels','match'),
    ('2026-08-10-progress-photos-schedule-integration.sql','column','progress_photos','wbs_node_id'),
    ('2026-08-10-progress-photos-schedule-integration.sql','column','progress_photos','activity_id'),
    ('2026-08-10-progress-photos-schedule-integration.sql','column','progress_photos','activity_name'),
    ('2026-08-11-drawing-register-scope.sql','column','drawing_register','scope'),
    ('2026-08-11-fix-privilege-escalation.sql','function','users_guard_self_escalation',''),
    ('2026-08-11-fix-privilege-escalation.sql','function','users_guard_self_insert',''),
    ('2026-08-12-delete-project-residue.sql','function','project_residue_tables',''),
    ('2026-08-12-delete-project-residue.sql','function','admin_delete_project',''),
    ('2026-08-12-delete-project-residue.sql','function','admin_project_delete_preview',''),
    ('2026-08-12-group-heads-replace-workspaces.sql','table','group_heads',''),
    ('2026-08-12-group-heads-replace-workspaces.sql','column','projects','group_head_id'),
    ('2026-08-12-group-heads-replace-workspaces.sql','function','admin_delete_group_head',''),
    ('2026-08-12-progress-photos-location-breakdown.sql','column','progress_photos','location_values'),
    ('2026-08-12-schedule-project-phase.sql','column','project_schedule','phase'),
    ('2026-08-12-schedule-project-phase.sql','column','wbs_nodes','phase'),
    ('2026-08-19-department-issues.sql','column','users','department'),
    ('2026-08-19-duration-scenarios-and-mom.sql','table','duration_scenarios',''),
    ('2026-08-19-duration-scenarios-and-mom.sql','table','meeting_minutes',''),
    ('2026-08-19-duration-scenarios-and-mom.sql','table','mom_items',''),
    ('2026-08-19-duration-scenarios-and-mom.sql','column','issues_lessons','mom_id'),
    ('2026-08-19-duration-scenarios-and-mom.sql','function','touch_updated_at',''),
    ('2026-08-19-eng-design-progress-mirror.sql','table','eng_design_progress',''),
    ('2026-08-19-packages.sql','table','packages',''),
    ('2026-08-19-packages.sql','function','packages_touch_updated_at',''),
    ('2026-08-19-schedule-contract-scope.sql','column','project_schedule','scope_type'),
    ('2026-08-19-schedule-contract-scope.sql','column','project_schedule','change_order_ref'),
    ('2026-08-19-schedule-contract-scope.sql','column','wbs_nodes','scope_type'),
    ('2026-08-19-schedule-contract-scope.sql','column','wbs_nodes','change_order_ref'),
    ('2026-08-19-schedule-package.sql','column','project_schedule','package_id'),
    ('2026-08-19-schedule-package.sql','column','wbs_nodes','package_id'),
    ('2026-08-19-schedule-package.sql','function','admin_delete_package',''),
    ('2026-08-20-department-minutes.sql','function','mom_is_mine',''),
    ('2026-08-20-department-minutes.sql','function','mom_has_raised',''),
    ('2026-08-21-class-codes.sql','table','class_codes',''),
    ('2026-08-21-class-codes.sql','column','project_schedule','class_code'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','mom_items','item_no'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','mom_items','category'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','mom_items','type'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','mom_items','issue'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','mom_items','carried_from_item_id'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','meeting_minutes','carried_from_mom_id'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','meeting_minutes','is_distributed'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','column','meeting_minutes','distributed_by'),
    ('2026-08-21-mom-schema-carryover-distribute.sql','function','mom_has_raised',''),
    ('2026-08-21-mom-schema-carryover-distribute.sql','function','mom_is_visible',''),
    ('2026-08-21-mom-schema-carryover-distribute.sql','function','mom_is_distributed',''),
    ('2026-08-21-mom-type-and-attachments.sql','column','meeting_minutes','meeting_type'),
    ('2026-08-21-mom-type-and-attachments.sql','column','mom_items','attachment_url'),
    ('2026-08-21-mom-type-and-attachments.sql','column','mom_items','attachment_name'),
    ('2026-08-21-schedule-split-change-orders.sql','column','project_schedule','split_group'),
    ('2026-08-21-schedule-split-change-orders.sql','column','project_schedule','split_seq'),
    ('2026-08-24-boq.sql','table','boq_revisions',''),
    ('2026-08-24-boq.sql','table','boq_items',''),
    ('2026-08-24-boq.sql','table','boq_import_profiles',''),
    ('2026-08-24-boq.sql','table','boq_class_map',''),
    ('2026-08-24-boq.sql','table','boq_class_suggestions',''),
    ('2026-08-24-boq.sql','table','boq_allocations',''),
    ('2026-08-24-boq.sql','table','boq_billing_periods',''),
    ('2026-08-24-boq.sql','table','boq_progress',''),
    ('2026-08-24-boq.sql','function','boq_touch_updated_at',''),
    ('2026-08-24-equipment-code-and-sharing.sql','table','equipment_tower_links',''),
    ('2026-08-24-equipment-code-and-sharing.sql','column','equipment_items','code'),
    ('2026-08-24-equipment-loading.sql','table','equipment_items',''),
    ('2026-08-24-equipment-loading.sql','table','equipment_loading',''),
    ('2026-08-24-equipment-loading.sql','table','equipment_site_plan',''),
    ('2026-08-24-equipment-loading.sql','function','project_location_values',''),
    ('2026-08-24-equipment-loading.sql','function','equipment_touch',''),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_mode'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_activity_id'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_wbs'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_label'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_qty'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','lead_months'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','lag_months'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_start'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_finish'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_items','link_synced_at'),
    ('2026-08-24-equipment-schedule-link.sql','column','equipment_loading','source'),
    ('2026-08-24-seasonal-calendars.sql','column','calendars','seasons'),
    ('2026-08-24-seasonal-calendars.sql','column','calendars','observe_special_days'),
    ('2026-08-24-seasonal-calendars.sql','column','calendars','climate_type'),
    ('2026-08-25-equipment-icons.sql','column','equipment_items','icon'),
    ('2026-08-25-package-adoption.sql','column','contracts_claims','package_id'),
    ('2026-08-25-package-adoption.sql','column','boq_items','package_id'),
    ('2026-08-25-pmi.sql','table','contract_profiles',''),
    ('2026-08-25-pmi.sql','table','contract_cost_terms',''),
    ('2026-08-25-pmi.sql','table','pmi_records',''),
    ('2026-08-25-pmi.sql','table','pmi_attachments',''),
    ('2026-08-25-pmi.sql','column','boq_items','pmi_id'),
    ('2026-08-25-pmi.sql','column','boq_revisions','pmi_id'),
    ('2026-08-25-pmi.sql','function','pmi_touch_updated_at',''),
    ('2026-08-25-schedule-cost-loading.sql','table','schedule_cost_loading',''),
    ('2026-08-25-vendor-identity.sql','table','wpm_vendors',''),
    ('2026-08-25-vendor-identity.sql','column','wpm_work_packages','vendor_id'),
    ('2026-08-25-vendor-identity.sql','column','wpm_work_packages','awarded_vendor_ids'),
    ('2026-08-25-vendor-identity.sql','column','wpm_work_packages','awarded_vendor_amounts'),
    ('2026-08-25-vendor-identity.sql','column','wpm_work_packages','contractor'),
    ('2026-08-25-vendor-identity.sql','column','productivity_activities','vendor_id'),
    ('2026-08-25-vendor-performance.sql','column','productivity_activities','work_package'),
    ('2026-08-25-vendor-performance.sql','function','schedule_scurve_agg_vendor',''),
    ('2026-08-25-vendor-performance.sql','function','vendor_scorecard_multi',''),
    ('2026-08-26-activity-cost-curve.sql','column','project_schedule','cost_curve'),
    ('2026-08-26-boq-claimed-vs-certified.sql','column','boq_progress','rel_pct_claimed'),
    ('2026-08-26-lessons-learned.sql','table','lessons_learned',''),
    ('2026-08-26-package-scoped-schedule.sql','table','schedule_builder',''),
    ('2026-08-26-package-scoped-schedule.sql','table','schedule_builder_pushes',''),
    ('2026-08-26-package-scoped-schedule.sql','column','wbs_nodes','is_package_root')
),
missing as (
  select e.* from expected e
  where (e.kind = 'table'    and to_regclass('public.' || e.obj) is null)
     or (e.kind = 'function' and not exists (
           select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public' and p.proname = e.obj))
     or (e.kind = 'column'   and to_regclass('public.' || e.obj) is not null
           and not exists (
           select 1 from information_schema.columns c
            where c.table_schema = 'public' and c.table_name = e.obj
              and c.column_name = e.col))
)
select migration,
       count(*) as missing_objects,
       string_agg(kind || ' ' || obj || coalesce('.' || nullif(col, ''), ''), ', '
                  order by kind, obj, col) as what_is_missing
  from missing
 group by migration
 order by migration;
